name: Publish Docker image for PR

on:
  pull_request:
    branches:
      - "**"

jobs:
  push_to_ghcr_registry:
    name: Push Docker image to GHCR.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta-httpd
        uses: docker/metadata-action@v5
        with:
          flavor: |
            suffix=-httpd
          images: ghcr.io/trajano/google-fonts
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: httpd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-httpd.outputs.tags }}
          labels: ${{ steps.meta-httpd.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-caddy
        uses: docker/metadata-action@v5
        with:
          flavor: |
            suffix=-caddy
          images: ghcr.io/trajano/google-fonts

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: caddy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-caddy.outputs.tags }}
          labels: ${{ steps.meta-caddy.outputs.labels }}
